name: tests

on: [push]

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: xcodebuild test -scheme BuonAPPetito -project BuonAPPetito.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0'
